printer.write("+-------------------------+\n")
printer.write("|LOGOLOGOLOGO LOGOLOGOLOGO|\n")
printer.write("|LOGOLOGOLOGO LOGOLOGOLOGO|\n")
printer.write("|LOGOLOGOLOGO LOGOLOGOLOGO|\n")
printer.write("|LOGOLOGOLOGO             |\n")
printer.write("|LOGOLOGOLOGO             |\n")
printer.write("|LOGOLOGOLOGO   Mar, 1994 |\n")
printer.write("|-------------------------|\n")
printer.write("|  MAIN NEWS STORY TITLE  |\n")
printer.write("|Lorem ipsum dolor sit    |\n")
printer.write("|amet, consectetur        |\n")
printer.write("|adipiscing elit. Morbi   |\n")
printer.write("|mollis sapien non        |\n")
printer.write("|elementum convallis.     |\n")
printer.write("|Vestibulum a velit cogue,|\n")
printer.write("|blandit odio vitae,      |\n")
printer.write("|malesuada tellus. Fusce  |\n")
printer.write("|ornare tortor sit amet.  |\n")
printer.write("|-------------------------|\n")
printer.write("|The MCity Times is paid  |\n")
printer.write("|for and sponsored by     |\n")
printer.write("|Honeydrop and RT Software|\n")
printer.write("+-------------------------+\n")
