printer.write("+-------------------------+\n")
printer.write("|THE MCITY TIMES| PAGE 02 |\n")
printer.write("|---------------+---------|\n")
printer.write("|  NEWS STORY TITLE HERE  |\n")
printer.write("|Lorem ipsum dolor sit    |\n")
printer.write("|amet, consectetur        |\n")
printer.write("|adipiscing elit. Duis    |\n")   
printer.write("|ligula massa, congue in  |\n")
printer.write("|viverra ornare, egestas  |\n")
printer.write("|nec orci. Nullam at      |\n")
printer.write("|placerat mi, vitae       |\n")
printer.write("|efficitur diam.          |\n")
printer.write("|-------------------------|\n")
printer.write("|  NEWS STORY TITLE HERE  |\n")
printer.write("|Lorem ipsum dolor sit    |\n") 
printer.write("|amet, consectetur        |\n")
printer.write("|adipiscing elit. Sed ac  |\n")
printer.write("|odio in mi placerat      |\n")
printer.write("|vulputate. Vivamus       |\n")
printer.write("|finibus massa at molestie|\n")
printer.write("|viverra. Pellentesque    |\n")
printer.write("|mattis, leo sit amet id. |\n")
printer.write("+-------------------------+\n")
