printer.write("+-------------------------+\n")
printer.write("|THE MCITY TIMES| PAGE 03 |\n")
printer.write("|---------------+---------|\n")
printer.write("|  NEWS STORY TITLE HERE  |\n")
printer.write("|Lorem ipsum dolor sit    |\n")
printer.write("|amet, consectetur        |\n")
printer.write("|adipiscing elit. Duis    |\n")   
printer.write("|ligula massa, congue in  |\n")
printer.write("|viverra ornare, egestas  |\n")
printer.write("|nec orci. Nullam at      |\n")
printer.write("|placerat mi, vitae       |\n")
printer.write("|efficitur diam.          |\n")
printer.write("|-------------------------|\n")
printer.write("|  GAME: THE DAILY ASCII  |\n")
printer.write("|                         |\n") 
printer.write("| Can you guess the ASCII |\n")
printer.write("|  character ID of these  |\n")
printer.write("|       characters?       |\n")
printer.write("|                         |\n")
printer.write("|  #1:   #2:   #3:   #4:  |\n")
printer.write("|   )     s     &     8   |\n")
printer.write("|   Answer on next page   |\n")
printer.write("+-------------------------+\n")
