printer.write("+-------------------------+\n")
printer.write("|THE MCITY TIMES| PAGE 04 |\n")
printer.write("|---------------+---------|\n")
printer.write("| ANSWER: THE DAILY ASCII |\n")
printer.write("|#1: Right Bracket     041|\n")
printer.write("|#2: Lowercase S       115|\n")
printer.write("|#3: Ampersand         038|\n")   
printer.write("|#4: Number Eight      056|\n")
printer.write("|-------------------------|\n")
printer.write("|  NEWS STORY TITLE HERE  |\n")
printer.write("|Lorem ipsum dolor sit    |\n") 
printer.write("|amet, consectetur        |\n")
printer.write("|adipiscing elit. Sed ac  |\n")
printer.write("|odio in mi placerat      |\n")
printer.write("|vulputate. Vivamus       |\n")
printer.write("|finibus massa at molestie|\n")
printer.write("|viverra. Pellentesque    |\n")
printer.write("|mattis, leo sit amet id. |\n")
printer.write("|-------------------------|\n")
printer.write("|The MCity Times is paid  |\n")
printer.write("|for and sponsored by     |\n")
printer.write("|Honeydrop and RT Software|\n")
printer.write("+-------------------------+\n")
